TWITTER_CONSUMER_KEY      = 'A4slsVEhbSjEqmRkGDudw'
TWITTER_CONSUMER_SECRET   = 'Bh9jGXYe7MXVCIFp0rcTYfvWCPUnFXvtBwBthONdao'
TWITTER_REQUEST_TOKEN_URL = 'http://twitter.com/oauth/request_token'
TWITTER_ACCESS_TOKEN_URL  = 'http://twitter.com/oauth/access_token'
TWITTER_AUTHORIZE_URL     = 'http://twitter.com/oauth/authorize'
TWITTER_URL               = 'http://twitter.com'
TWITTER_CALLBACK_URL      = 'http://localhost:4567'
#TWITTER_CALLBACK_URL      = 'http://stay-with-a-local.slslabs.com'

require 'twitter_oauth'